application: mirror-api-service
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /packages
  static_dir: static/packages

- url: /demo\.css
  static_files: static/demo.css
  upload: static/demo\.css

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /demo.dart
  static_files: static/demo.dart
  upload: static/demo\.dart

- url: /demo.dart.js
  static_files: static/demo.dart.js
  upload: static/demo\.dart\.js

- url: .*
  script: main.app


